window.marketingCurriculum = {
    brand: {
        ar: [
            { title: "تقسيم السوق وفهم الجمهور", body: `التسويق يبدأ بفهم مجموعة أشخاص لديهم حاجة مشتركة، لا بمخاطبة الجميع. قسّم السوق وفق المشكلة أو السلوك أو السياق، ثم اختر شريحة يمكن الوصول إليها وخدمتها بميزة واضحة.\n\nابنِ وصفاً عملياً للعميل من مقابلات ومراجعة أسئلة الدعم والبحث، لا من افتراضات مثل العمر وحده. سجّل المهمة التي يريد إنجازها، العائق، البديل الحالي، ومعيار الاختيار.`, challenge: "قابل ثلاثة عملاء محتملين واسألهم عن آخر مرة واجهوا فيها هذه المشكلة، وما الحل الذي استخدموه." },
            { title: "التموضع والقيمة المقترحة", body: `التموضع هو المكان الذي تريد أن تحتله علامتك في ذهن جمهور محدد مقارنة بالبدائل. القيمة المقترحة توضّح لمن تخدم، وما النتيجة التي تقدمها، ولماذا يصدقك العميل. اربط الميزة بمنفعة ملموسة ودليل يمكن التحقق منه.\n\nاكتب صيغة أولية: «لـ[الجمهور] الذي يحتاج[النتيجة]، نقدم[الحل] مع[اختلاف مثبت]». اختبر وضوحها؛ إذا احتاجت إلى فقرة طويلة كي تُفهم، بسّطها.`, challenge: "اكتب جملة تموضع لمشروعك، ثم اطلب من خمسة أشخاص إعادة شرحها بكلماتهم." },
            { title: "رحلة العميل وبناء الثقة", body: `تختلف أسئلة الشخص الذي يسمع بعلامتك لأول مرة عن أسئلة من يقارن الأسعار أو يستعد للشراء. ارسم المراحل من الوعي إلى التقييم والقرار ثم الاستخدام والعودة، وحدّد السؤال والدليل المناسبين لكل مرحلة.\n\nتتكون الثقة من تجربة متسقة: وصف صادق، سعر واضح، خطوات شراء مفهومة، دعم سريع، ووعود يمكن تنفيذها. اجمع ملاحظات العملاء بعد كل مرحلة وحسّن أكثر نقطة تسبب التردد أو الانقطاع.`, challenge: "ارسم رحلة شراء واحدة واكتب سؤال العميل ودليلاً يساعده في كل مرحلة." }
        ],
        en: [
            { title: "Market segmentation and audience research", body: `Marketing starts with a group of people who share a need, not a message aimed at everyone. Segment by problem, behavior, or situation, then choose a group you can reach and serve with a clear advantage.\n\nBuild a practical customer profile from interviews, support questions, and search behavior rather than assumptions such as age alone. Record the job to be done, the barrier, the current alternative, and the choice criteria.`, challenge: "Interview three potential customers about the last time they faced this problem and what they did instead." },
            { title: "Positioning and value proposition", body: `Positioning is the place you want your brand to occupy in a specific audience’s mind relative to alternatives. A value proposition states who you help, what outcome you provide, and why a customer should believe you. Connect a feature to a tangible benefit and verifiable proof.\n\nDraft: “For [audience] who need [outcome], we provide [solution] with [proven difference].” Test for clarity. If people need a paragraph to understand it, simplify.`, challenge: "Write a positioning statement, then ask five people to explain it back in their own words." },
            { title: "Customer journey and trust", body: `Someone discovering your brand has different questions from a person comparing prices or preparing to buy. Map awareness, evaluation, decision, use, and return; identify the question and useful evidence at each stage.\n\nTrust comes from a consistent experience: honest descriptions, clear pricing, understandable purchase steps, responsive support, and promises you can keep. Collect feedback at each stage and improve the point that causes the most hesitation or drop-off.`, challenge: "Map one buying journey and write the customer’s question and helpful proof for every stage." }
        ],
        fr: [
            { title: "Segmentation et étude du public", body: `Le marketing commence par un groupe de personnes ayant un besoin commun, pas par un message destiné à tout le monde. Segmentez selon le problème, le comportement ou la situation, puis choisissez un public que vous pouvez atteindre et servir avec un avantage clair.\n\nConstruisez un profil à partir d’entretiens, de demandes au support et de recherches, plutôt que d’hypothèses comme l’âge seul. Notez le besoin, le frein, la solution actuelle et les critères de choix.`, challenge: "Interrogez trois clients potentiels sur la dernière fois où ils ont rencontré ce problème et sur leur solution." },
            { title: "Positionnement et proposition de valeur", body: `Le positionnement est la place que votre marque veut occuper dans l’esprit d’un public précis face aux alternatives. La proposition de valeur indique qui vous aidez, quel résultat vous apportez et pourquoi le client peut vous croire. Reliez une caractéristique à un bénéfice concret et vérifiable.\n\nRédigez : « Pour [public] qui cherche [résultat], nous proposons [solution] avec [différence prouvée]. » Testez la clarté. Si une longue explication est nécessaire, simplifiez.`, challenge: "Rédigez votre positionnement, puis demandez à cinq personnes de le reformuler avec leurs mots." },
            { title: "Parcours client et confiance", body: `Une personne qui découvre votre marque n’a pas les mêmes questions qu’une personne qui compare les prix ou s’apprête à acheter. Cartographiez la découverte, l’évaluation, la décision, l’utilisation et le retour ; identifiez la question et la preuve utile à chaque étape.\n\nLa confiance repose sur une expérience cohérente : description honnête, prix clair, achat compréhensible, assistance réactive et promesses tenues. Recueillez les retours à chaque étape et améliorez le point qui crée le plus d’hésitation.`, challenge: "Cartographiez un parcours d’achat et notez la question du client et la preuve utile à chaque étape." }
        ]
    },
    content: {
        ar: [
            { title: "ركائز المحتوى وأهدافه", body: `ابدأ بهدف واضح: تعريف الجمهور بمشكلة، شرح حل، بناء ثقة، أو دعم قرار الشراء. أنشئ ركائز متكررة مثل التعليم، الدليل، الكواليس، ودراسة الحالة كي لا يتحول النشر إلى أفكار عشوائية.\n\nاربط كل قطعة بمرحلة من رحلة العميل وحدّد جمهوراً واحداً وفكرة واحدة ودعوة مناسبة. المحتوى الجيد يجيب عن سؤال حقيقي أو يساعد على خطوة عملية؛ كثرة النشر وحدها ليست استراتيجية.`, challenge: "اختر ثلاثة أسئلة متكررة من جمهورك وحوّل كل سؤال إلى فكرة محتوى وهدف ومؤشر نجاح." },
            { title: "التقويم التحريري والصيغ", body: `حوّل الركائز إلى تقويم واقعي يحدد الموضوع، الصيغة، المنصة، المسؤول، وموعد النشر. اختَر الصيغة بحسب الفكرة: شرح متسلسل لمفهوم، فيديو لعرض تطبيق، أو صفحة تفصيلية للموضوع الذي يحتاج بحثاً.\n\nأعد توظيف الفكرة مع تكييفها للمنصة، لا بنسخ النص نفسه. أضف ترجمة للفيديو، وصفاً مفيداً للصور، وعناوين واضحة. اترك مساحة للأسئلة والأحداث الجديدة بدلاً من ملء كل يوم بمنشور.`, challenge: "خطط لأسبوعين بمنشورين مفيدين أسبوعياً، وحدد لكل منهما صيغة ودعوة ومقياساً." },
            { title: "التوزيع وقياس الأداء", body: `النشر هو بداية التوزيع. شارك المحتوى حيث يبحث جمهورك، تعاون مع شركاء مناسبين، واستخدم الإعلانات فقط عندما تعرف من تريد الوصول إليه وما الذي سيحدث بعد المشاهدة.\n\nاقرأ المؤشر بحسب الهدف: الوصول للانتشار، الحفظ والمشاركة للفائدة، النقر للانتقال، والتحويل للنتيجة. استخدم روابط موسومة وسجل النتائج؛ كرر الأنماط الناجحة مع اختبار تحسين واحد في كل مرة.`, challenge: "اختر قطعة محتوى، واكتب هدفها ومؤشرها ومصدر الزيارات والقرار الذي ستتخذه بعد أسبوع." }
        ],
        en: [
            { title: "Content pillars and goals", body: `Begin with a clear job: introduce a problem, explain a solution, build trust, or support a purchase decision. Use recurring pillars such as education, evidence, behind-the-scenes, and case studies so publishing does not become random.\n\nConnect every item to a journey stage, one audience, one idea, and a fitting call to action. Useful content answers a real question or enables a practical next step; posting frequency alone is not a strategy.`, challenge: "Choose three recurring audience questions and turn each into a content idea, goal, and success metric." },
            { title: "Editorial planning and formats", body: `Turn pillars into a realistic calendar with topic, format, channel, owner, and publish date. Choose the format for the idea: a sequence for a concept, a video for a demonstration, or a detailed page for a topic that needs research.\n\nRepurpose the idea with platform-specific edits rather than copying the same post everywhere. Caption video, describe images usefully, and use clear headings. Leave room for new questions and events instead of filling every day with a post.`, challenge: "Plan two useful posts a week for two weeks; assign each a format, call to action, and metric." },
            { title: "Distribution and performance", body: `Publishing is the start of distribution. Share where your audience looks, collaborate with relevant partners, and use paid promotion only when you know whom to reach and what should happen next.\n\nChoose metrics by goal: reach for distribution, saves and shares for usefulness, clicks for visits, and conversions for outcomes. Use tagged links and record results; repeat useful patterns while testing one improvement at a time.`, challenge: "Choose one post and write its goal, metric, traffic source, and the decision you will make after a week." }
        ],
        fr: [
            { title: "Piliers éditoriaux et objectifs", body: `Commencez par un objectif clair : présenter un problème, expliquer une solution, créer la confiance ou faciliter une décision d’achat. Définissez des piliers récurrents comme la pédagogie, les preuves, les coulisses et les études de cas.\n\nReliez chaque contenu à une étape du parcours, à un public, à une idée et à un appel à l’action adaptés. Un contenu utile répond à une vraie question ou aide à avancer ; publier souvent ne constitue pas une stratégie.`, challenge: "Choisissez trois questions fréquentes du public et transformez-les en idées, objectifs et indicateurs." },
            { title: "Calendrier éditorial et formats", body: `Transformez vos piliers en calendrier réaliste : sujet, format, canal, responsable et date. Choisissez le format selon l’idée : une série pour expliquer un concept, une vidéo pour une démonstration ou une page détaillée pour un sujet exigeant.\n\nRéutilisez l’idée en l’adaptant à la plateforme, au lieu de copier le même texte partout. Sous-titrez les vidéos, décrivez les images et structurez avec des titres clairs. Gardez de la place pour les nouvelles questions.`, challenge: "Planifiez deux contenus utiles par semaine pendant deux semaines avec format, appel à l’action et indicateur." },
            { title: "Diffusion et mesure", body: `La publication lance la diffusion. Partagez là où votre public cherche, collaborez avec des partenaires pertinents et ne payez la promotion que si vous savez qui toucher et quelle action proposer.\n\nChoisissez les indicateurs selon l’objectif : portée pour la diffusion, enregistrements et partages pour l’utilité, clics pour les visites et conversions pour les résultats. Balisez vos liens, notez les résultats et testez une amélioration à la fois.`, challenge: "Choisissez une publication et notez son objectif, son indicateur, sa source de trafic et la décision après une semaine." }
        ]
    },
    campaign: {
        ar: [
            { title: "الأهداف والقياس قبل الإطلاق", body: `حدّد نتيجة العمل أولاً: مبيعات، طلبات مؤهلة، تسجيل، أو زيارة متجر. اختر حدث تحويل يعكس تلك النتيجة واختبر تسجيله قبل إنفاق المال. اربط الروابط بمعايير UTM ثابتة لتعرف المصدر والحملة والإبداع.\n\nاحسب سقف تكلفة الاكتساب انطلاقاً من هامش الربح وقيمة العميل، لا من ميزانية المنافس. لا تخلط الإيراد المنسوب للحملة بالربح؛ يجب احتساب الخصم والمرتجعات وتكاليف الخدمة.`, challenge: "اكتب هدف حملة واحداً، وحدث التحويل، ومصدر البيانات، وأقصى تكلفة مقبولة قبل الإطلاق." },
            { title: "الجمهور والعرض والإبداع", body: `اجعل العرض واضحاً ومناسباً لمرحلة العميل: تجربة، حزمة، أو حل لمشكلة محددة. اختر جمهوراً يمكن وصف حاجته، مع احترام إعدادات الخصوصية وعدم استهداف الصفات الحساسة.\n\nالإعلان الفعال يوصل فكرة واحدة بسرعة: افتتاحية تلفت الجمهور، منفعة محددة، دليل موثوق، وخطوة تالية. اختبر زوايا إبداعية مختلفة فعلاً، وتأكد أن صفحة الوصول تكمل الوعد نفسه.`, challenge: "اكتب نسختين لجمهور واحد: غيّر زاوية الرسالة فقط، وثبّت العرض والصفحة ومقياس التحويل." },
            { title: "الاختبار والتحسين والتوسّع", body: `ابدأ بميزانية ومدة تسمحان بجمع بيانات كافية، ثم غيّر متغيراً واضحاً واحداً مثل الرسالة أو الصورة. لا تحكم على حملة من ساعات قليلة أو من النقرات وحدها؛ افحص جودة العملاء والتحويل النهائي.\n\nأوقف النسخ وفق قاعدة محددة مسبقاً، وسجل ما تعلمته. وسّع الإنفاق تدريجياً عندما يكون القياس سليماً والنتيجة مستقرة، مع مراقبة تكرار الإعلان وتشبع الجمهور وهامش الربح.`, challenge: "ضع قاعدة إيقاف وتوسيع مكتوبة، ثم صمم اختباراً يغيّر متغيراً واحداً فقط." }
        ],
        en: [
            { title: "Objectives and tracking before launch", body: `Define the business outcome first: sales, qualified leads, sign-ups, or store visits. Choose a conversion event that represents it and test tracking before spending. Use consistent UTM parameters to identify source, campaign, and creative.\n\nSet an acquisition-cost ceiling from margin and customer value, not a competitor’s budget. Attributed revenue is not profit; account for discounts, returns, and service costs.`, challenge: "Write one campaign objective, conversion event, data source, and maximum acceptable cost before launch." },
            { title: "Audience, offer, and creative", body: `Make the offer clear and suited to the customer’s stage: a trial, bundle, or solution to a specific problem. Choose an audience whose need you can describe; respect privacy settings and avoid sensitive targeting.\n\nA useful ad communicates one idea quickly: an audience-relevant opening, a specific benefit, credible proof, and a next step. Test genuinely different creative angles and make sure the landing page continues the same promise.`, challenge: "Write two ads for one audience. Change only the message angle; keep offer, page, and conversion metric fixed." },
            { title: "Testing, optimization, and scaling", body: `Use a budget and duration that can produce enough signal, then change one clear variable such as message or image. Do not judge from a few hours or clicks alone; inspect lead quality and final conversion.\n\nPause variants using a rule set before launch and record what you learned. Increase spend gradually only when tracking is sound and results are stable; monitor frequency, audience fatigue, and margin.`, challenge: "Write a stop-and-scale rule, then design a test that changes only one variable." }
        ],
        fr: [
            { title: "Objectifs et suivi avant lancement", body: `Définissez d’abord le résultat commercial : ventes, prospects qualifiés, inscriptions ou visites en magasin. Choisissez un événement de conversion qui le représente et testez le suivi avant toute dépense. Utilisez des paramètres UTM cohérents.\n\nFixez le coût d’acquisition maximal selon la marge et la valeur client, pas selon le budget d’un concurrent. Le chiffre d’affaires attribué n’est pas le bénéfice : tenez compte des remises, retours et coûts de service.`, challenge: "Avant le lancement, notez l’objectif, l’événement de conversion, la source de données et le coût maximal accepté." },
            { title: "Public, offre et création", body: `Formulez une offre claire adaptée au parcours : essai, lot ou réponse à un problème précis. Définissez un public et son besoin, respectez les paramètres de confidentialité et évitez le ciblage sensible.\n\nUne publicité efficace transmet une idée : une accroche pertinente, un bénéfice concret, une preuve crédible et une prochaine étape. Testez des angles réellement différents et faites correspondre la page d’arrivée à la promesse.`, challenge: "Rédigez deux annonces pour un public : changez uniquement l’angle, gardez offre, page et indicateur identiques." },
            { title: "Tests, optimisation et développement", body: `Prévoyez un budget et une durée permettant d’obtenir un signal suffisant, puis changez une seule variable claire : message ou visuel. Ne concluez pas après quelques heures ni à partir des clics seuls ; vérifiez la qualité des prospects et la conversion finale.\n\nArrêtez les variantes selon une règle définie avant le lancement et consignez les apprentissages. Augmentez progressivement les dépenses quand le suivi est fiable et les résultats stables ; surveillez la fréquence, la fatigue du public et la marge.`, challenge: "Écrivez une règle d’arrêt et d’augmentation, puis concevez un test qui ne change qu’une variable." }
        ]
    },
    social: {
        ar: [
            { title: "اختيار المنصات ودور كل قناة", body: `اختر المنصة حيث يقضي جمهورك وقته وحيث تستطيع إنتاج صيغة جيدة باستمرار. لا يلزم الوجود في كل مكان. حدّد دور القناة: اكتشاف، خدمة، بناء مجتمع، أو تحويل، ثم اربطها بباقي الرحلة.\n\nراجع ملاءمة الجمهور، نوع المحتوى، الموارد، وإمكانية قياس النتائج. ابدأ بقناة رئيسية وأخرى مساندة، وحدّد ما الذي ستتوقف عن فعله إذا لم تحقق القناة قيمة.`, challenge: "قارن ثلاث منصات وفق الجمهور والصيغة والموارد والدور، ثم اختر واحدة للبداية وعلّل اختيارك." },
            { title: "النشر وبناء المجتمع", body: `أنشئ إيقاعاً قابلاً للاستمرار وتقويماً مبنياً على أسئلة الجمهور. استخدم مزيجاً من التعليم والدليل والمحادثة والعروض؛ واجعل الدعوات للتفاعل طبيعية ومتصلة بالموضوع.\n\nضع إرشادات للرد: زمن استجابة متوقع، نبرة ثابتة، متى تنتقل المحادثة إلى الخاص، ومتى تصعّد شكوى أو تهديداً. تعامل مع النقد المشروع بشفافية، ولا تطلب بيانات شخصية علناً.`, challenge: "اكتب ثلاث قواعد مجتمعية وخطوات رد على سؤال، شكوى، ومعلومة خاطئة." },
            { title: "التحليل والمخاطر", body: `قِس ما يطابق وظيفة القناة: نمو الوصول للوعي، حفظ ومشاركة للمحتوى المفيد، وزمن الاستجابة للخدمة. افصل بين نمو المتابعين وبين أثر العمل التجاري، وراقب الزيارات والتحويلات مع مصدر واضح.\n\nراقب الشائعات، انتحال الحسابات، وظهور بيانات خاصة. جهّز مالكاً للتصعيد ومساراً داخلياً للتحقق قبل الرد، وحدّث الخطة بعد كل حادثة بدلاً من الارتجال وقت الأزمة.`, challenge: "اختر مؤشرين للقناة، وسجّل خط البداية وموعد المراجعة واسم المسؤول عن الرد والتصعيد." }
        ],
        en: [
            { title: "Choosing platforms and channel roles", body: `Choose a platform where your audience spends time and where you can consistently make a strong format. You do not need to be everywhere. Give each channel a role: discovery, service, community, or conversion, and connect it to the wider journey.\n\nCompare audience fit, format, resources, and measurability. Begin with one primary channel and one supporting channel. Decide what work you would stop if a channel provides no value.`, challenge: "Compare three platforms by audience, format, resources, and role; choose one to start and explain why." },
            { title: "Publishing and community building", body: `Set a sustainable cadence and plan around audience questions. Mix education, evidence, conversation, and offers; keep calls for interaction natural and relevant.\n\nDefine response guidance: expected response time, voice, when to move to a private channel, and when to escalate a complaint or threat. Address fair criticism transparently and never request personal information in public.`, challenge: "Write three community standards and a response flow for a question, complaint, and false claim." },
            { title: "Measurement and risk", body: `Measure the channel’s job: reach growth for awareness, saves and shares for useful content, and response time for service. Separate follower growth from business impact; track visits and conversions with a clear source.\n\nWatch for misinformation, impersonation, and exposed personal data. Assign an escalation owner and a verification process before responding. Update the plan after incidents instead of improvising during a crisis.`, challenge: "Choose two channel metrics, record a baseline and review date, and name who owns response and escalation." }
        ],
        fr: [
            { title: "Choisir les plateformes et leur rôle", body: `Choisissez une plateforme utilisée par votre public et adaptée à un format que vous pouvez produire régulièrement. Il n’est pas nécessaire d’être partout. Attribuez à chaque canal un rôle : découverte, service, communauté ou conversion.\n\nComparez public, formats, ressources et mesure possible. Commencez par un canal principal et un canal complémentaire. Décidez aussi ce que vous arrêterez si un canal n’apporte aucune valeur.`, challenge: "Comparez trois plateformes selon public, format, ressources et rôle, puis justifiez votre choix de départ." },
            { title: "Publication et animation de communauté", body: `Adoptez un rythme tenable et planifiez à partir des questions du public. Alternez pédagogie, preuves, échanges et offres ; gardez des appels à l’interaction naturels et pertinents.\n\nDéfinissez les réponses : délai, ton, passage en privé et escalade d’une réclamation ou menace. Répondez avec transparence aux critiques légitimes et ne demandez jamais de données personnelles en public.`, challenge: "Rédigez trois règles de communauté et une procédure pour une question, une réclamation et une fausse information." },
            { title: "Mesure et gestion des risques", body: `Mesurez le rôle du canal : portée pour la notoriété, enregistrements et partages pour l’utilité, délai de réponse pour le service. Distinguez croissance des abonnés et impact commercial ; suivez visites et conversions avec une source claire.\n\nSurveillez les fausses informations, l’usurpation et l’exposition de données personnelles. Désignez un responsable d’escalade et vérifiez les faits avant de répondre. Mettez à jour la procédure après chaque incident.`, challenge: "Choisissez deux indicateurs, notez leur niveau de départ et la date de revue, puis désignez les responsables." }
        ]
    },
    analytics: {
        ar: [
            { title: "مسار التحويل وتعريف المؤشرات", body: `ابدأ بسؤال القرار الذي ستدعمه البيانات. ارسم المسار من الظهور إلى الزيارة ثم التسجيل أو الشراء والعودة. عرّف لكل مرحلة حدثاً واضحاً ومؤشراً له بسط ومقام وفترة ثابتة.\n\nمعدل التحويل = عدد التحويلات ÷ الزيارات المؤهلة. تكلفة الاكتساب = تكاليف التسويق والمبيعات ÷ العملاء الجدد في الفترة ذاتها. لا تقارن أرقاماً بتعريفات مختلفة أو بفترات غير متكافئة.`, challenge: "عرّف حدثاً ومؤشراً لكل مرحلة، ثم اكتب مصدر البيانات ومالك القرار." },
            { title: "مصادر الزيارات والإسناد", body: `استخدم أسماء UTM موحدة للمصدر والوسيط والحملة والمحتوى، وتحقق من الروابط قبل توزيعها. افصل الزيارات المباشرة والعضوية والمدفوعة، وانتبه إلى أن إعدادات الخصوصية والأجهزة قد تمنع ربط كل زيارة بتحويل.\n\nالإسناد يصف طريقة توزيع الفضل بين نقاط التفاعل، وليس حقيقة سببية كاملة. ROAS يساوي الإيراد المنسوب للإعلان ÷ الإنفاق الإعلاني، لكنه لا يساوي الربح ولا يحسب تلقائياً أثر الخصومات أو المرتجعات.`, challenge: "صمم معيار UTM لحملة واحدة واكتب ثلاثة أسباب قد تجعل التحويل غير منسوب بدقة." },
            { title: "التجارب والتقارير والقرار", body: `قبل الاختبار، اكتب الفرضية والمتغير والنتيجة الأساسية ومدة الاختبار. غيّر عاملاً واحداً كلما أمكن، وتجنب إيقاف الاختبار مبكراً لمجرد ظهور نتيجة مؤقتة. تأكد من حجم عينة معقول ومن عدم تداخل الحملات.\n\nقدّم التقرير كسؤال، نتيجة، حدود، وقرار تالٍ. افحص الموسمية وجودة القياس وتركيبة الجمهور، ولا تخلط الارتباط بالسببية. الهدف ليس جمع لوحات أكثر؛ الهدف قرار أفضل يمكن مراجعته.`, challenge: "اكتب فرضية اختبار ومقياساً أساسياً وحداً أدنى للمدة، ثم دوّن حدود الاستنتاج." }
        ],
        en: [
            { title: "Conversion journey and metric definitions", body: `Begin with the decision the data should support. Map exposure to visit, sign-up or purchase, and return. Define a clear event and a metric with a stable numerator, denominator, and time window for every stage.\n\nConversion rate = conversions ÷ qualified visits. Acquisition cost = marketing and sales cost ÷ new customers in the same period. Do not compare metrics with different definitions or unlike time windows.`, challenge: "Define one event and metric per journey stage, then name its data source and decision owner." },
            { title: "Traffic sources and attribution", body: `Use consistent UTM names for source, medium, campaign, and content, and verify links before distribution. Separate direct, organic, and paid visits. Privacy settings and device changes can prevent some visits from being linked to a conversion.\n\nAttribution describes how credit is assigned across touchpoints; it is not complete proof of causation. ROAS is attributed ad revenue ÷ ad spend, but it is not profit and does not automatically account for discounts or returns.`, challenge: "Design a UTM convention for one campaign and list three reasons a conversion may not be attributed accurately." },
            { title: "Experiments, reporting, and decisions", body: `Before a test, write the hypothesis, variable, primary outcome, and duration. Change one factor where possible and avoid stopping early because of a temporary result. Ensure the sample is useful and campaigns do not overlap.\n\nReport the question, result, limitations, and next decision. Check seasonality, measurement quality, and audience mix; do not confuse correlation with causation. The goal is not more dashboards but a better decision you can revisit.`, challenge: "Write a test hypothesis, primary metric, minimum duration, and one limitation on what you can conclude." }
        ],
        fr: [
            { title: "Parcours de conversion et définition des indicateurs", body: `Commencez par la décision à éclairer. Cartographiez l’exposition, la visite, l’inscription ou l’achat, puis le retour. Définissez un événement clair et un indicateur avec numérateur, dénominateur et période stables pour chaque étape.\n\nTaux de conversion = conversions ÷ visites qualifiées. Coût d’acquisition = dépenses marketing et commerciales ÷ nouveaux clients sur la même période. Ne comparez pas des définitions ou périodes différentes.`, challenge: "Définissez un événement et un indicateur par étape, puis indiquez la source et le responsable de décision." },
            { title: "Sources de trafic et attribution", body: `Utilisez des noms UTM cohérents pour la source, le support, la campagne et le contenu, puis vérifiez les liens. Distinguez trafic direct, naturel et payant. Les paramètres de confidentialité et les changements d’appareil peuvent empêcher le rapprochement de certaines visites.\n\nL’attribution répartit le crédit entre les interactions ; elle ne prouve pas entièrement la causalité. Le ROAS correspond au chiffre d’affaires attribué ÷ dépenses publicitaires, mais ce n’est pas le bénéfice et il ne tient pas automatiquement compte des remises et retours.`, challenge: "Créez une convention UTM et citez trois raisons pour lesquelles une conversion peut être mal attribuée." },
            { title: "Expériences, rapports et décisions", body: `Avant un test, rédigez l’hypothèse, la variable, le résultat principal et la durée. Changez si possible un seul facteur et évitez d’arrêter trop tôt sur un résultat provisoire. Vérifiez la taille de l’échantillon et le chevauchement des campagnes.\n\nPrésentez la question, le résultat, les limites et la décision suivante. Vérifiez saisonnalité, qualité de mesure et composition du public ; ne confondez pas corrélation et causalité. L’objectif est une meilleure décision, pas davantage de tableaux de bord.`, challenge: "Rédigez une hypothèse, un indicateur principal, une durée minimale et une limite d’interprétation." }
        ]
    },
    copywriting: {
        ar: [
            { title: "بحث الجمهور والمنفعة", body: `اجمع الكلمات التي يستخدمها العملاء من المقابلات والتقييمات وأسئلة البحث. افهم ما يريدون إنجازه وما الذي يمنعهم. حوّل مواصفة المنتج إلى منفعة يلاحظونها، ولا تفترض أن الميزة تشرح قيمتها بنفسها.\n\nاكتب لشخص واحد في موقف محدد. الدقة أقوى من عبارات عامة مثل «حل مبتكر». تجنب الادعاءات المطلقة أو الصحية والمالية التي لا تستطيع إثباتها، واطلب إذناً قبل استخدام شهادة عميل.`, challenge: "اجمع خمس عبارات حقيقية من العملاء، ثم اكتب منفعة واحدة مدعومة بدليل لكل عبارة." },
            { title: "بناء الرسالة والدليل", body: `نظّم الرسالة: افتتاحية مرتبطة بحاجة، المشكلة أو الرغبة، الحل والمنفعة، دليل مناسب، ثم دعوة واحدة. اختر دليلاً صادقاً: طريقة العمل، تجربة موثقة، سياسة شفافة، أو رقم مع سياقه.\n\nالعنوان الجيد يحدد الجمهور أو النتيجة ويطابق محتوى الصفحة. احذف الحشو، وفضّل الأفعال المباشرة والجمل القصيرة. اجعل المخاطر والقيود واضحة، ولا تستخدم ندرة أو استعجالاً مصطنعاً.`, challenge: "اكتب عنوانين للمنفعة نفسها، وأضف دليلاً واحداً يمكن للقارئ التحقق منه." },
            { title: "صفحات الهبوط والاختبار", body: `يجب أن تكمل صفحة الهبوط وعد الإعلان: عنوان متطابق، منفعة واضحة، شرح موجز، دليل، إجابات عن الاعتراضات، ودعوة بارزة. اطلب أقل قدر ضروري من البيانات واجعل الصفحة سهلة على الهاتف.\n\nاختبر تغييراً واحداً له فرضية، مثل العنوان أو ترتيب الدليل، وحدد مسبقاً مقياس النجاح. راقب جودة العملاء والإكمال، لا معدل النقر فقط، ولا تخفِ شروط السعر أو الإلغاء.`, challenge: "راجع صفحة موجودة: هل يتطابق العنوان مع الإعلان؟ هل تظهر المنفعة والدليل والدعوة قبل التمرير؟" }
        ],
        en: [
            { title: "Audience research and customer benefit", body: `Collect customer language from interviews, reviews, and search questions. Learn what people are trying to accomplish and what blocks them. Translate a product feature into a benefit they can notice; a feature does not explain its own value.\n\nWrite for one person in a specific situation. Specificity beats vague claims such as “innovative solution.” Avoid absolute, health, or financial claims you cannot substantiate, and get permission before using a testimonial.`, challenge: "Collect five real customer phrases and write one evidence-backed benefit for each." },
            { title: "Message structure and proof", body: `Organize a message as a relevant opening, problem or desire, solution and benefit, suitable proof, then one call to action. Use honest evidence: process details, documented results, transparent policies, or a number with context.\n\nA strong headline identifies an audience or outcome and matches the page. Remove filler; prefer direct verbs and short sentences. State risks and limits clearly, and do not manufacture scarcity or urgency.`, challenge: "Write two headlines for one benefit and add one proof point a reader can verify." },
            { title: "Landing pages and testing", body: `A landing page should continue the ad’s promise: matching headline, clear benefit, concise explanation, proof, answers to objections, and a visible call to action. Ask only for necessary data and make the page work well on mobile.\n\nTest one change with a hypothesis, such as headline or proof order, and define success in advance. Track lead quality and completion, not click-through rate alone. Do not hide pricing or cancellation terms.`, challenge: "Review a page: does its headline match the ad, and are benefit, proof, and action clear before scrolling?" }
        ],
        fr: [
            { title: "Étude du public et bénéfice client", body: `Recueillez les mots des clients dans les entretiens, avis et recherches. Comprenez leur objectif et ce qui les freine. Transformez une caractéristique en bénéfice concret ; la caractéristique ne suffit pas à démontrer sa valeur.\n\nÉcrivez pour une personne dans une situation précise. La précision vaut mieux qu’une promesse vague comme « solution innovante ». Évitez les affirmations absolues, médicales ou financières invérifiables et demandez l’accord avant tout témoignage.`, challenge: "Relevez cinq expressions réelles de clients et formulez pour chacune un bénéfice accompagné d’une preuve." },
            { title: "Structure du message et preuve", body: `Structurez le message : accroche liée au besoin, problème ou désir, solution et bénéfice, preuve pertinente, puis un seul appel à l’action. Choisissez une preuve honnête : méthode, résultat documenté, politique transparente ou chiffre contextualisé.\n\nUn bon titre précise le public ou le résultat et correspond à la page. Supprimez le superflu, privilégiez les verbes directs et phrases courtes. Présentez clairement les limites ; ne créez pas de fausse urgence.`, challenge: "Écrivez deux titres pour le même bénéfice et ajoutez une preuve vérifiable par le lecteur." },
            { title: "Pages d’atterrissage et tests", body: `La page doit prolonger la promesse de la publicité : titre cohérent, bénéfice clair, explication concise, preuve, réponses aux objections et appel à l’action visible. Ne demandez que les données nécessaires et adaptez la page au mobile.\n\nTestez une modification selon une hypothèse, par exemple le titre ou l’ordre des preuves, et définissez le succès à l’avance. Mesurez la qualité des prospects et les finalisations, pas seulement les clics. N’escamotez ni prix ni conditions d’annulation.`, challenge: "Examinez une page : le titre correspond-il à la publicité, et bénéfice, preuve et action sont-ils visibles sans défiler ?" }
        ]
    },
    seo: {
        ar: [
            { title: "نية البحث وبحث الكلمات", body: `تحسين الظهور في البحث يبدأ بما يحاول الشخص إنجازه. ميّز بين نية التعلّم والمقارنة والشراء، واجمع الأسئلة والعبارات التي يستخدمها جمهورك فعلاً. اختر موضوعاً تستطيع الإجابة عنه بخبرة ومعلومة نافعة، لا كلمة ذات حجم بحث مرتفع فقط.\n\nقيّم صلة العبارة بالعرض، ونية الباحث، والمنافسة، وقدرتك على تقديم إجابة أفضل. اجمع الموضوعات القريبة في صفحات مترابطة بدلاً من إنشاء صفحة سطحية لكل صيغة متشابهة.`, challenge: "اختر استعلاماً واحداً، واكتب نية الباحث والصفحة التي تجيب عنه والدليل الذي ستقدمه." },
            { title: "أساسيات الصفحة والتقنية", body: `اجعل كل صفحة مفهومة للإنسان ومحركات البحث: عنواناً وصفياً فريداً، عنواناً رئيسياً واضحاً، بنية عناوين منطقية، وروابط داخلية تصف الصفحة المقصودة. استخدم وصفاً بديلاً للصور المهمة وتأكد من سهولة الاستخدام على الهاتف.\n\nتحقق من إمكانية الزحف والفهرسة، وحالة الروابط، وملف sitemap، والصفحات المكررة أو المعطوبة. البيانات المنظمة قد تساعد على تفسير المحتوى لكنها لا تضمن ظهوراً خاصاً. الأداء الجيد يدعم التجربة ولا يضمن ترتيباً بعينه.`, challenge: "راجع صفحة: هل يمكن فهم موضوعها من العنوان والرابط؟ هل تعمل على الهاتف وتصل إليها الروابط الداخلية؟" },
            { title: "المحتوى والقياس المستمر", body: `قدّم إجابة أصلية مكتملة ومحدثة، واذكر المصادر عند الحاجة، وأظهر الخبرة والمسؤولية في الموضوع. لا تحشو الكلمات ولا تنشئ صفحات آلية متكررة. اربط الصفحة بخطوة مفيدة مثل درس مرتبط أو استشارة واضحة.\n\nاستخدم أدوات مشرفي المواقع لمراجعة الاستعلامات والنقرات والفهرسة، ثم راقب التحويلات في التحليلات. قيّم الاتجاه على مدى أسابيع أو أشهر، وحدّث الصفحة عندما تتغير الحقائق أو تظهر أسئلة جديدة.`, challenge: "اختر صفحة قديمة، وحدد معلومة تحتاج تحديثاً وسؤالاً ناقصاً ومؤشراً واحداً لمراجعة أثر التحديث." }
        ],
        en: [
            { title: "Search intent and keyword research", body: `Search optimization starts with what a person is trying to accomplish. Distinguish learning, comparison, and purchase intent; collect the questions and phrases your audience actually uses. Choose a topic you can answer with useful expertise, not just high search volume.\n\nAssess relevance to your offer, likely intent, competition, and your ability to provide a better answer. Group related topics into useful, connected pages rather than thin pages for near-identical phrases.`, challenge: "Choose one query and write its likely intent, the page that should answer it, and the evidence you will provide." },
            { title: "On-page and technical foundations", body: `Make each page clear to people and search systems: a unique descriptive title, one clear main heading, logical heading structure, and internal links that describe their destination. Add useful alternative text to meaningful images and check mobile usability.\n\nCheck crawlability, index status, broken links, the sitemap, and duplicate pages. Structured data can help systems interpret content but does not guarantee a special result. Good performance supports usability; it does not guarantee a particular ranking.`, challenge: "Review a page: is its topic clear from the title and URL, does it work on mobile, and do useful internal links reach it?" },
            { title: "Useful content and ongoing measurement", body: `Create original, complete, current answers and cite sources where appropriate. Show relevant experience and accountability. Avoid keyword stuffing and repeated automated pages. Connect the page to a helpful next step such as a related course or clear consultation offer.\n\nUse search performance tools to review queries, clicks, and indexing, then measure conversions in analytics. Assess trends over weeks or months and refresh the page when facts change or new audience questions emerge.`, challenge: "Choose an older page; identify one fact to update, one missing question, and one metric to review afterward." }
        ],
        fr: [
            { title: "Intention de recherche et mots-clés", body: `Le référencement commence par l’objectif de la personne. Distinguez recherche d’information, comparaison et achat ; relevez les questions et expressions réellement utilisées par votre public. Choisissez un sujet auquel vous pouvez répondre avec expertise, pas seulement un mot très recherché.\n\nÉvaluez la pertinence pour votre offre, l’intention, la concurrence et votre capacité à apporter une meilleure réponse. Regroupez les sujets proches dans des pages utiles plutôt que de créer des pages superficielles pour des variantes quasi identiques.`, challenge: "Choisissez une requête et notez son intention, la page qui doit y répondre et la preuve à fournir." },
            { title: "Fondamentaux techniques et de page", body: `Rendez chaque page claire : titre descriptif unique, titre principal explicite, structure logique et liens internes indiquant leur destination. Ajoutez un texte alternatif utile aux images importantes et vérifiez l’expérience mobile.\n\nContrôlez l’exploration et l’indexation, les liens cassés, le sitemap et les doublons. Les données structurées aident à interpréter le contenu sans garantir un affichage spécial. La performance améliore l’usage, mais ne garantit pas un classement précis.`, challenge: "Vérifiez une page : sujet clair dans le titre et l’URL, bon affichage mobile et liens internes utiles." },
            { title: "Contenu utile et mesure continue", body: `Proposez des réponses originales, complètes et à jour ; citez les sources si nécessaire et démontrez votre expérience. Évitez le bourrage de mots-clés et les pages répétitives automatisées. Reliez la page à une prochaine étape utile.\n\nConsultez les outils de performance de recherche pour suivre requêtes, clics et indexation, puis mesurez les conversions dans vos outils d’analyse. Évaluez les tendances sur plusieurs semaines et actualisez la page lorsque les faits ou les questions évoluent.`, challenge: "Choisissez une ancienne page : notez un fait à actualiser, une question manquante et un indicateur à vérifier." }
        ]
    },
    email: {
        ar: [
            { title: "الموافقة وجودة القائمة", body: `ابدأ بقائمة أرسل أصحابها موافقة واضحة على نوع الرسائل وتواترها. اجمع الحد الأدنى من البيانات، وبيّن سبب جمعها، واحفظ سجلاً للموافقة. لا تشترِ قوائم ولا تضف عناوين من دون إذن؛ فذلك يضر الثقة والتسليم وقد يخالف القانون.\n\nقسّم القائمة وفق تفضيلات أو سلوك ذي صلة، مثل اهتمام معلن أو شراء سابق. أتح للمشترك اختيار التواتر والموضوع، ونظّف العناوين المرتدة وغير النشطة وفق سياسة مدروسة.`, challenge: "راجع نموذج الاشتراك واكتب ما الذي يوافق عليه المستخدم وكيف يعدّل تفضيلاته أو ينسحب." },
            { title: "تصميم الرسالة والتسليم", body: `اجعل الموضوع صادقاً ومحدداً، وأضف نصاً تمهيدياً يشرح القيمة. ابدأ بأهم فائدة، واكتب فقرات قصيرة، ووجّه إلى دعوة أساسية واحدة. استخدم تصميماً يعمل على الهاتف، ونصاً بديلاً للصور، ورابطاً واضحاً لإلغاء الاشتراك.\n\nاستخدم نطاق إرسال موثّقاً وإعدادات مصادقة مناسبة، وراقب الارتداد والشكاوى. لا تضمن كلمة «مجاناً» أو تغيير اسم المرسل الوصول إلى صندوق الوارد؛ جودة القائمة ومحتوى الرسالة وسمعة النطاق عوامل مؤثرة.`, challenge: "اكتب موضوعين صادقين للرسالة نفسها، ثم اختبر وضوح الدعوة والقراءة على شاشة هاتف." },
            { title: "الأتمتة والاحتفاظ بالعملاء", body: `أنشئ رسائل آلية مرتبطة بفعل مفيد: ترحيب بعد اشتراك مؤكد، إرشاد بعد الشراء، أو تذكير اختياري عند توقف استخدام الخدمة. اجعل التوقيت والمحتوى متوقعين، وحدد شروط الإيقاف حتى لا تستمر الرسائل بعد الانسحاب أو حل المشكلة.\n\nقِس التسليم والنقر والتحويل والإيراد لكل مستلم مع الشكاوى والانسحاب. قارِن الشرائح والفترات، ولا تعتبر فتح الرسالة مقياساً دقيقاً دائماً. أرسل ما يضيف قيمة، وقلّل التواتر إذا ظهرت علامات الإرهاق.`, challenge: "ارسم تسلسل ترحيب من ثلاث رسائل وحدد لكل واحدة سبب الإرسال وقاعدة التوقف ومؤشر النجاح." }
        ],
        en: [
            { title: "Permission and list quality", body: `Start with a clear opt-in that explains the type and frequency of messages. Collect only necessary data, explain why it is needed, and retain consent records. Do not buy lists or add addresses without permission; it harms trust and deliverability and may violate law.\n\nSegment by relevant preference or behavior, such as a stated interest or prior purchase. Let subscribers manage topics and frequency, and handle bounced or inactive addresses under a considered policy.`, challenge: "Review a sign-up form: what exactly does the person agree to, and how can they change preferences or unsubscribe?" },
            { title: "Message design and deliverability", body: `Use an honest, specific subject line and a preheader that explains the value. Lead with the main benefit, use short paragraphs, and focus on one primary call to action. Design for mobile, provide image alternatives, and make unsubscribe clear.\n\nUse a verified sending domain and appropriate authentication; monitor bounces and complaints. No magic word or sender-name change guarantees the inbox. List quality, message content, and domain reputation all matter.`, challenge: "Write two honest subject lines for one email, then check its action and mobile readability." },
            { title: "Automation and customer retention", body: `Trigger automated messages after a useful event: confirmed welcome, post-purchase guidance, or an optional reminder after inactivity. Make timing and content predictable, and define stop conditions so messages do not continue after unsubscribe or issue resolution.\n\nMeasure delivery, clicks, conversion, and revenue per recipient alongside complaints and unsubscribes. Compare segments and time periods; opens are not always a reliable metric. Send only when useful and reduce frequency when fatigue appears.`, challenge: "Map a three-message welcome flow; define the reason, stop rule, and success metric for every message." }
        ],
        fr: [
            { title: "Consentement et qualité de la liste", body: `Commencez par un consentement explicite qui précise le type et la fréquence des messages. Collectez uniquement les données nécessaires, expliquez leur usage et conservez la preuve du consentement. N’achetez pas de listes et n’ajoutez pas d’adresses sans accord : cela nuit à la confiance et à la délivrabilité, et peut être illégal.\n\nSegmentez selon une préférence ou un comportement pertinent. Laissez choisir les sujets et la fréquence, puis gérez les adresses invalides ou inactives selon une politique définie.`, challenge: "Examinez un formulaire : à quoi la personne consent-elle et comment peut-elle modifier ses choix ou se désinscrire ?" },
            { title: "Conception et délivrabilité", body: `Choisissez un objet honnête et précis, avec un pré-en-tête qui annonce la valeur. Commencez par le bénéfice principal, utilisez des paragraphes courts et un appel à l’action. Adaptez la mise en page au mobile, décrivez les images et rendez la désinscription claire.\n\nAuthentifiez votre domaine d’envoi et surveillez rebonds et plaintes. Aucun mot magique ni nom d’expéditeur ne garantit la boîte de réception. La qualité de la liste, le contenu et la réputation du domaine comptent.`, challenge: "Rédigez deux objets honnêtes, puis vérifiez l’appel à l’action et la lecture sur mobile." },
            { title: "Automatisation et fidélisation", body: `Déclenchez les messages après une action utile : bienvenue après confirmation, conseils après achat ou rappel facultatif après inactivité. Rendez le calendrier prévisible et définissez des conditions d’arrêt après désinscription ou résolution du problème.\n\nMesurez livraison, clics, conversions et revenu par destinataire, ainsi que plaintes et désinscriptions. Comparez segments et périodes ; l’ouverture n’est pas toujours fiable. Envoyez quand le message est utile et réduisez la fréquence en cas de fatigue.`, challenge: "Dessinez une séquence de bienvenue de trois messages ; définissez raison, règle d’arrêt et indicateur pour chacun." }
        ]
    },
    plan: {
        ar: [
            { title: "تحليل الوضع وتحديد الهدف", body: `ابدأ بخط أساس: حجم السوق المتاح، شرائح العملاء، البدائل، نقاط القوة والقيود، والنتائج الحالية. استخدم بيانات العملاء والمبيعات والبحث، وافصل بين الحقيقة والافتراض. لا تجعل تحليل SWOT قائمة عامة بلا قرار.\n\nحوّل هدف العمل إلى نتيجة تسويقية محددة لها جمهور وموعد ومقياس، مثل زيادة الطلبات المؤهلة مع الحفاظ على تكلفة اكتساب ضمن هامش محدد. سجّل خط البداية والافتراضات والمخاطر.`, challenge: "اكتب هدفاً تسويقياً واحداً وحدد خط البداية والمقياس والموعد والافتراض الذي يجب اختباره." },
            { title: "القنوات والميزانية والاقتصاد", body: `وزّع العمل بين قنوات الاكتشاف والتقييم والتحويل والاحتفاظ بحسب الجمهور والدليل المتاح، لا بحسب الموضة. احسب تكلفة الإنتاج والتشغيل والإنفاق الإعلامي، وحدد ميزانية تعلم صغيرة للاختبارات قبل التوسع.\n\nاربط الاستثمار بهامش الربح وقيمة العميل وفترة استرداد التكلفة. لا تفترض أن آخر نقرة صنعت الطلب كله؛ بعض القنوات تبني الوعي ولا تظهر في الإسناد المباشر. ضع سيناريو محافظاً ومتوقعاً وحداً لإيقاف الخطة.`, challenge: "قسّم ميزانية افتراضية بين إنتاج وتوزيع واختبار، واشرح الفرضية ومقياس القرار لكل بند." },
            { title: "التنفيذ والحوكمة والتحسين", body: `حوّل الخطة إلى تقويم ومسؤول وموعد وتسليم واضح لكل نشاط. اربط الرسائل عبر القنوات، وحدد اعتماد المحتوى والموافقات والخصوصية وخطة التعامل مع التعليقات أو الأعطال.\n\nراجع مؤشرات التنفيذ والنتيجة في مواعيد ثابتة، وسجّل ما تغيّر ولماذا. إذا أخفقت قناة، اختبر هل السبب الجمهور أم العرض أم الرسالة أم القياس قبل نقل الميزانية. أوقف العمل الذي لا يدعم الهدف ودوّن الدروس للدورة التالية.`, challenge: "أنشئ خطة شهرية بثلاثة أنشطة، ومالك لكل نشاط، وموعد، ومؤشر، وقاعدة مراجعة." }
        ],
        en: [
            { title: "Situation analysis and objectives", body: `Establish a baseline: addressable market, customer segments, alternatives, strengths and constraints, and current results. Use customer, sales, and research evidence; separate facts from assumptions. Do not turn SWOT into a generic list without a decision.\n\nTranslate a business goal into a specific marketing outcome with an audience, deadline, and metric, such as increasing qualified demand while keeping acquisition cost within a defined margin. Record the baseline, assumptions, and risks.`, challenge: "Write one marketing objective and define its baseline, metric, deadline, and assumption to test." },
            { title: "Channels, budget, and unit economics", body: `Allocate work across discovery, evaluation, conversion, and retention channels based on audience and evidence, not trend. Estimate production, operations, and media costs; reserve a learning budget for tests before scaling.\n\nRelate investment to margin, customer value, and payback period. Do not assume last-click created all demand; some awareness channels are undercounted by direct attribution. Set conservative and expected scenarios and a stop limit.`, challenge: "Split a sample budget across production, distribution, and testing; state each assumption and decision metric." },
            { title: "Execution, governance, and improvement", body: `Turn the plan into a calendar with an owner, date, and clear deliverable for each activity. Coordinate messages across channels and define approvals, privacy checks, and response plans for comments or outages.\n\nReview activity and outcome metrics on a schedule and record what changed and why. If a channel underperforms, test whether the cause is audience, offer, message, or tracking before moving budget. Stop work that does not support the goal and capture lessons for the next cycle.`, challenge: "Create a one-month plan with three activities, an owner, date, metric, and review rule for each." }
        ],
        fr: [
            { title: "Analyse de situation et objectifs", body: `Établissez un point de départ : marché adressable, segments, alternatives, forces et limites, résultats actuels. Appuyez-vous sur les clients, ventes et recherches ; distinguez faits et hypothèses. Une analyse SWOT ne doit pas rester une liste sans décision.\n\nTraduisez l’objectif commercial en résultat marketing précis avec public, échéance et indicateur, par exemple augmenter les demandes qualifiées tout en maintenant le coût d’acquisition sous une limite de marge. Notez la base, les hypothèses et les risques.`, challenge: "Rédigez un objectif marketing et précisez son niveau de départ, son indicateur, son échéance et l’hypothèse à tester." },
            { title: "Canaux, budget et rentabilité", body: `Répartissez les efforts entre découverte, évaluation, conversion et fidélisation selon le public et les preuves, pas selon les tendances. Estimez production, opérations et diffusion ; réservez un budget d’apprentissage avant d’augmenter les dépenses.\n\nReliez l’investissement à la marge, à la valeur client et au délai de retour. Le dernier clic ne crée pas toute la demande ; certains canaux de notoriété sont peu visibles en attribution directe. Définissez scénarios prudent et attendu, ainsi qu’un seuil d’arrêt.`, challenge: "Répartissez un budget fictif entre production, diffusion et tests ; notez les hypothèses et indicateurs associés." },
            { title: "Exécution, gouvernance et amélioration", body: `Transformez le plan en calendrier avec responsable, échéance et livrable pour chaque activité. Coordonnez les messages et définissez validations, contrôles de confidentialité et procédures en cas de plainte ou panne.\n\nExaminez régulièrement indicateurs d’activité et résultats, puis notez les changements et leurs raisons. Si un canal échoue, testez public, offre, message et mesure avant de déplacer le budget. Arrêtez les actions sans lien avec l’objectif et conservez les apprentissages.`, challenge: "Créez un plan mensuel de trois actions avec responsable, date, indicateur et règle de revue." }
        ]
    },
    influencer: {
        ar: [
            { title: "اختيار الشريك ومطابقة الجمهور", body: `اختيار صانع المحتوى لا يبدأ بعدد المتابعين. قارن تطابق جمهوره مع عملائك، وجودة التفاعل، وطريقة تقديمه، وسلامة المحتوى السابق. اطلب بيانات عن متوسط المشاهدات ومصادر الجمهور، وراجع عينة من التعليقات للتأكد من أنها حقيقية وذات صلة.\n\nحدّد هدف التعاون قبل التواصل: اكتشاف، تجربة منتج، زيارات مؤهلة، أو مبيعات قابلة للتتبع. اختر مقياساً أساسياً يناسب الهدف، ولا تدفع مقابل وصول لا يخدم جمهورك.`, challenge: "قارن ثلاثة صنّاع محتوى وفق تطابق الجمهور وجودة التفاعل والهدف، ثم اختر واحداً وعلّل قرارك." },
            { title: "الاتفاق والإفصاح والحقوق", body: `اكتب موجزاً يوضح الجمهور والرسالة والنقاط التي يجب ذكرها، مع ترك مساحة لصوت المبدع الحقيقي. اتفق كتابياً على التسليمات والمواعيد والمراجعات والأجر وحقوق إعادة الاستخدام والإلغاء.\n\nيجب الإفصاح بوضوح عن العلاقة المدفوعة وفق القواعد المحلية والمنصة. لا تطلب ادعاءات غير مثبتة، واطلب موافقة صريحة قبل استخدام المحتوى في إعلان أو قناة أخرى.`, challenge: "اكتب موجز تعاون من صفحة واحدة يتضمن التسليمات والأجر والحقوق والإفصاح ومقياس النجاح." },
            { title: "قياس الأثر وبناء العلاقة", body: `استخدم روابط أو رموزاً مميزة لكل شريك، وحدد نافذة القياس وطريقة احتساب النتائج قبل الإطلاق. افصل بين الوصول والتفاعل والزيارات والتحويلات، وراجع جودة العملاء وهامش الربح لا إجمالي النقرات فقط.\n\nشارك النتائج مع المبدع باحترام، واحتفظ بما تعلمته عن الرسائل والجمهور. التعاون المتكرر ينجح عندما تكون القيمة متبادلة والتوقعات واضحة، وليس عندما تتحول العلاقة إلى منشورات متكررة بلا هدف.`, challenge: "صمم لوحة متابعة لتعاون واحد فيها ثلاثة مؤشرات، مصدر بيانات، موعد مراجعة، وقرار استمرار أو تعديل." }
        ],
        en: [
            { title: "Choosing a partner and audience fit", body: `Creator selection should not start with follower count. Compare audience overlap with your customers, engagement quality, presentation style, and the safety of past content. Ask for average view data and audience sources, then review a sample of comments for relevance and authenticity.\n\nSet the collaboration goal before outreach: awareness, product trial, qualified visits, or attributable sales. Choose a primary metric that fits the goal; do not pay for reach that misses your audience.`, challenge: "Compare three creators by audience fit, engagement quality, and campaign goal; choose one and explain why." },
            { title: "Briefs, disclosure, and usage rights", body: `Write a brief that explains the audience, message, and required facts while leaving room for the creator's authentic voice. Agree in writing on deliverables, dates, revisions, payment, reuse rights, and cancellation terms.\n\nClearly disclose paid relationships under applicable local rules and platform policies. Do not request unsupported claims, and get explicit permission before using creator content in ads or other channels.`, challenge: "Draft a one-page collaboration brief covering deliverables, payment, rights, disclosure, and success metric." },
            { title: "Measuring impact and building partnerships", body: `Use a unique link or code for each partner, and define the measurement window and attribution method before launch. Separate reach, engagement, visits, and conversions; review lead quality and margin, not clicks alone.\n\nShare results respectfully and record what you learned about the message and audience. Repeat partnerships work when value is mutual and expectations are clear, not when posts are repeated without a goal.`, challenge: "Design a partner scorecard with three metrics, data sources, a review date, and a continue-or-adjust decision." }
        ],
        fr: [
            { title: "Choisir un partenaire et vérifier l’affinité", body: `Le choix d’un créateur ne commence pas par le nombre d’abonnés. Comparez la proximité de son public avec vos clients, la qualité des échanges, son style et la sécurité de ses contenus précédents. Demandez les vues moyennes et les sources d’audience, puis examinez les commentaires pour vérifier leur pertinence.\n\nDéfinissez l’objectif avant le contact : notoriété, essai, visites qualifiées ou ventes attribuables. Choisissez un indicateur principal adapté ; ne payez pas pour une portée qui ne touche pas votre public.`, challenge: "Comparez trois créateurs selon l’affinité du public, la qualité des échanges et l’objectif ; choisissez-en un et justifiez votre choix." },
            { title: "Brief, transparence et droits d’utilisation", body: `Rédigez un brief précisant le public, le message et les informations indispensables, tout en respectant la voix du créateur. Convenez par écrit des livrables, dates, révisions, rémunération, droits de réutilisation et conditions d’annulation.\n\nSignalez clairement tout partenariat rémunéré selon les règles locales et celles de la plateforme. Évitez les affirmations non prouvées et demandez une autorisation explicite avant de réutiliser le contenu dans une publicité ou un autre canal.`, challenge: "Rédigez un brief d’une page avec livrables, rémunération, droits, transparence et indicateur de réussite." },
            { title: "Mesurer l’impact et construire la relation", body: `Utilisez un lien ou un code distinct pour chaque partenaire et définissez avant le lancement la période et la méthode d’attribution. Distinguez portée, interactions, visites et conversions ; examinez la qualité des prospects et la marge, pas seulement les clics.\n\nPartagez les résultats avec respect et consignez les apprentissages sur le message et le public. Une collaboration durable repose sur une valeur réciproque et des attentes claires, pas sur des publications répétées sans objectif.`, challenge: "Créez une fiche partenaire avec trois indicateurs, leurs sources, une date de revue et une décision de poursuivre ou d’ajuster." }
        ]
    },
    ecommerce: {
        ar: [
            { title: "صفحة المنتج التي تجيب عن أسئلة المشتري", body: `يحتاج الزائر إلى فهم ما الذي سيحصل عليه، ولمن يناسب المنتج، وما الذي يميّزه. استخدم عنواناً محدداً، وصوراً واضحة، ومواصفات دقيقة، وفوائد مرتبطة بحاجات العميل. أظهر السعر والتوفر والتوصيل والإرجاع قبل أن يضطر المستخدم للبحث عنها.\n\nاستخدم أسئلة العملاء ومراجعاتهم لتحسين الوصف، ولا تخفِ القيود أو تبالغ في النتائج. اجعل زر الشراء واضحاً وصفحة المنتج سهلة القراءة على الهاتف.`, challenge: "راجع صفحة منتج واكتب ثلاثة أسئلة تبقى بلا إجابة، ثم حدّد أين تضيف الإجابات والدليل." },
            { title: "الثقة وإتمام الشراء", body: `كل خطوة إضافية أو مفاجأة في السعر قد تجعل العميل يتراجع. اعرض تكلفة التوصيل والضرائب والوقت المتوقع مبكراً، واطلب البيانات الضرورية فقط. وفّر طريقة دفع مألوفة ورسائل واضحة عن أمان الدفع وحالة الطلب.\n\nاختبر مسار الشراء على الهاتف بنفسك، بما في ذلك الأخطاء واستعادة السلة. راقب أين يتوقف الزوار، واستعن بتعليقات الدعم لا بالتخمين وحده.`, challenge: "أكمل عملية شراء تجريبية على الهاتف وسجّل كل موضع تردد أو معلومة ناقصة أو خطوة زائدة." },
            { title: "التحسين بالتجربة والقياس", body: `ابدأ بخط أساس لمعدل إضافة المنتج إلى السلة، وبدء الدفع، وإتمام الطلب، ومتوسط قيمة السلة. افصل بين أنواع الأجهزة ومصادر الزيارات، وتأكد من سلامة الأحداث قبل تفسير النتائج.\n\nرتّب التحسينات بحسب أثرها المحتمل وسهولة اختبارها. غيّر عنصراً واحداً في كل تجربة، مثل ترتيب المعلومات أو تكلفة التوصيل المعروضة، وسجّل النتيجة والحدود قبل تعميم التغيير.`, challenge: "اختر نقطة تسرب واحدة في مسار الشراء، واكتب فرضية ومقياساً وخطوة اختبار وشرطاً لاعتماد التغيير." }
        ],
        en: [
            { title: "Product pages that answer buyer questions", body: `Visitors need to know what they receive, who the product suits, and what makes it different. Use a specific title, clear images, accurate specifications, and benefits connected to customer needs. Show price, availability, delivery, and returns before shoppers have to search for them.\n\nUse customer questions and reviews to improve the description; do not hide limitations or overstate outcomes. Keep the purchase action clear and the page easy to read on mobile.`, challenge: "Review one product page, list three unanswered buyer questions, and decide where to add answers and evidence." },
            { title: "Trust and checkout completion", body: `Every extra step or surprise cost can make a buyer leave. Show delivery costs, taxes, and expected timing early, and request only necessary information. Offer familiar payment methods and clear messages about payment security and order status.\n\nTest the whole checkout on a phone, including error recovery and cart return. Track where people stop, and use support questions as evidence rather than relying on guesses.`, challenge: "Complete a test purchase on a phone and record every hesitation, missing detail, or unnecessary step." },
            { title: "Experimentation and measurement", body: `Set a baseline for add-to-cart, checkout starts, completed orders, and average order value. Separate device types and traffic sources, and validate event tracking before interpreting results.\n\nPrioritize improvements by likely impact and testability. Change one element per experiment, such as information order or delivery-cost presentation, and record results and limitations before rolling out a change.`, challenge: "Choose one checkout drop-off point and write a hypothesis, metric, test, and rule for adopting the change." }
        ],
        fr: [
            { title: "Des fiches produit qui répondent aux questions", body: `Le visiteur doit comprendre ce qu’il recevra, à qui le produit convient et ce qui le distingue. Utilisez un titre précis, des images claires, des caractéristiques exactes et des bénéfices liés aux besoins. Affichez prix, disponibilité, livraison et retours sans obliger l’acheteur à les chercher.\n\nAppuyez-vous sur les questions et avis des clients, sans cacher les limites ni exagérer les résultats. Rendez l’action d’achat visible et la page facile à lire sur mobile.`, challenge: "Examinez une fiche produit, relevez trois questions sans réponse et indiquez où ajouter réponses et preuves." },
            { title: "Confiance et finalisation du paiement", body: `Chaque étape supplémentaire ou frais inattendu peut faire partir l’acheteur. Présentez tôt les frais, taxes et délais de livraison, et ne demandez que les informations nécessaires. Proposez des moyens de paiement connus et des informations claires sur la sécurité et le suivi de commande.\n\nTestez le paiement complet sur téléphone, y compris la gestion des erreurs et le retour au panier. Repérez les abandons et utilisez les questions du support comme preuves.`, challenge: "Effectuez un achat test sur téléphone et notez chaque hésitation, information manquante ou étape inutile." },
            { title: "Expérimentation et mesure", body: `Établissez une base pour l’ajout au panier, le début du paiement, les commandes finalisées et le panier moyen. Distinguez appareils et sources de trafic, puis vérifiez le suivi des événements avant d’interpréter les résultats.\n\nPriorisez les améliorations selon leur impact potentiel et leur facilité de test. Ne changez qu’un élément par expérience, consignez résultats et limites avant le déploiement.`, challenge: "Choisissez un point d’abandon, puis formulez une hypothèse, un indicateur, un test et une règle de validation." }
        ]
    },
    automation: {
        ar: [
            { title: "التقسيم حسب الاحتياج ومرحلة العميل", body: `الأتمتة الجيدة تبدأ بفهم ما يحتاجه الشخص، لا بإرسال أكبر عدد من الرسائل. قسّم العملاء حسب سلوك واضح ومفيد، مثل التسجيل، أو شراء منتج، أو طلب مساعدة. استخدم أقل قدر من البيانات ووضّح سبب جمعها، واحترم الموافقة وتفضيلات التواصل.\n\nاربط كل شريحة بهدف خدمة محدد. لا تستنتج صفات حساسة ولا ترسل محتوى شخصياً يتجاوز ما يتوقعه المستخدم.`, challenge: "عرّف ثلاث شرائح سلوكية، ولكل واحدة اكتب حاجتها ورسالة نافعة ومعلومة لا ينبغي جمعها." },
            { title: "تصميم المسار وقواعد التوقف", body: `ارسم مساراً بسيطاً يبدأ بحدث واضح، ثم رسالة أو خطوة مفيدة، ثم متابعة مناسبة. مثال: بعد التسجيل المؤكد تصل رسالة ترحيب، وبعد أيام يصل مورد مرتبط بالاهتمام المعلن. اجعل التوقيت متوقعاً ولا تكرر الرسائل من مسارات متعددة.\n\nضع قواعد توقف عند إلغاء الاشتراك أو إتمام الهدف أو حل المشكلة، وأضف مراجعة بشرية للقرارات الحساسة. اختبر المسار بعنوان ومحتوى وروابط صحيحة قبل تشغيله.`, challenge: "ارسم مساراً من ثلاث خطوات، وحدد لكل خطوة الحدث والرسالة والتوقيت وشرط التوقف." },
            { title: "القياس والتحسين المسؤول", body: `راقب التسليم والنقر والتحويل والشكاوى والانسحاب، مع تعريف ثابت لكل مؤشر. قارِن مجموعة تتلقى المسار بمجموعة مناسبة لا تتلقاه عندما يكون ذلك ممكناً، حتى لا تنسب كل نتيجة للأتمتة وحدها.\n\nراجع التكرار واللغة والتوقيت بانتظام. أوقف المسار إذا زادت الشكاوى أو أصبحت الرسائل غير ملائمة، واحتفظ بسجل للتغييرات وسببها.`, challenge: "اكتب خطة مراجعة شهرية فيها مؤشرات نجاح وحماية، وعتبة توقف، ومسؤول يتابع النتائج." }
        ],
        en: [
            { title: "Segment by need and customer stage", body: `Good automation starts by understanding what someone needs, not by sending more messages. Segment by useful, observable behavior such as signing up, buying a product, or asking for help. Use only necessary data, explain why it is collected, and respect consent and communication preferences.\n\nGive every segment a service goal. Do not infer sensitive traits or send personalization beyond what people reasonably expect.`, challenge: "Define three behavioral segments; for each, write a need, a useful message, and data you should not collect." },
            { title: "Journey design and stop rules", body: `Map a simple journey from a clear trigger to a useful message or action and a relevant follow-up. For example, send a welcome after confirmed sign-up, then a resource related to a stated interest. Make timing predictable and prevent duplicate messages from overlapping journeys.\n\nStop after unsubscribe, goal completion, or issue resolution, and add human review for sensitive decisions. Test the full journey, links, and message content before activation.`, challenge: "Map a three-step journey and define each trigger, message, timing, and stop condition." },
            { title: "Measurement and responsible optimization", body: `Track delivery, clicks, conversion, complaints, and unsubscribes with stable definitions. When possible, compare recipients with a suitable group that does not receive the journey so you do not attribute every outcome to automation.\n\nReview frequency, language, and timing regularly. Pause a journey if complaints rise or messages become irrelevant, and keep a record of changes and reasons.`, challenge: "Write a monthly review plan with success and guardrail metrics, a stop threshold, and an owner." }
        ],
        fr: [
            { title: "Segmenter selon le besoin et l’étape client", body: `Une bonne automatisation commence par le besoin, pas par l’envoi de davantage de messages. Segmentez selon des comportements utiles et observables : inscription, achat ou demande d’aide. Limitez les données, expliquez leur collecte et respectez consentement et préférences.\n\nAssociez chaque segment à un objectif de service. Ne déduisez pas de caractéristiques sensibles et évitez toute personnalisation que la personne ne peut raisonnablement attendre.`, challenge: "Définissez trois segments comportementaux ; notez pour chacun un besoin, un message utile et une donnée à ne pas collecter." },
            { title: "Concevoir un parcours et ses règles d’arrêt", body: `Dessinez un parcours simple : un déclencheur clair, un message ou une action utile, puis un suivi pertinent. Par exemple, envoyez un accueil après confirmation, puis une ressource liée à un intérêt déclaré. Rendez le rythme prévisible et évitez les messages en double.\n\nArrêtez après désinscription, objectif atteint ou problème résolu ; prévoyez une vérification humaine pour les décisions sensibles. Testez le parcours, les liens et les contenus avant activation.`, challenge: "Dessinez un parcours de trois étapes avec déclencheur, message, délai et condition d’arrêt." },
            { title: "Mesure et optimisation responsable", body: `Suivez délivrabilité, clics, conversions, plaintes et désinscriptions avec des définitions stables. Si possible, comparez les destinataires à un groupe similaire non exposé afin de ne pas attribuer tous les résultats à l’automatisation.\n\nRévisez régulièrement fréquence, langage et calendrier. Suspendez le parcours si les plaintes augmentent ou si les messages deviennent inadaptés, et consignez les modifications et leurs raisons.`, challenge: "Rédigez un plan de revue mensuelle avec indicateurs de réussite et de protection, seuil d’arrêt et responsable." }
        ]
    }
};
